"""Shared utilities for trace HTML pages.

All trace pages generated by this project use the same timeago
banner pattern: a span at the top showing how long ago the page
was generated, updated live by a 1-second JS tick.  This module
extracts the pattern so every renderer can include it without
duplicating the boilerplate.

Usage in a renderer:

    from trace_render_utils import timeago_assets, timeago_banner

    css = MY_CSS + timeago_assets.css
    body = (
        timeago_banner("Generated", message_suffix=" • my-page-X")
        + timeago_assets.script
        + ...
    )

The page must include the ``.timeago`` and ``.gen-banner`` CSS
plus the script that ticks ``.timeago`` elements every second.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone


# ---------------------------------------------------------------------------
# Assets — CSS + JS for the timeago banner
# ---------------------------------------------------------------------------


_TIMEAGO_CSS = """\
.gen-banner { background: #fff8e1; border: 1px solid #fbc02d;
              border-radius: 4px; padding: 8px 12px;
              font-size: 12px; margin: 10px 0; }
.gen-banner code { font-family: 'Courier New', monospace;
                   background: rgba(0,0,0,0.05); padding: 1px 4px;
                   border-radius: 2px; }
.gen-banner .timeago { font-weight: bold; color: #e65100; }
"""


_TIMEAGO_SCRIPT = """\
<script>
function _fmt_ago(s){if(s<5)return'just now';if(s<60)return s+' second'+(s===1?'':'s')+' ago';if(s<3600){const m=Math.floor(s/60);return m+' minute'+(m===1?'':'s')+' ago';}if(s<86400){const h=Math.floor(s/3600);return h+' hour'+(h===1?'':'s')+' ago';}const d=Math.floor(s/86400);return d+' day'+(d===1?'':'s')+' ago';}
function _tick(){document.querySelectorAll('.timeago').forEach(el=>{const gen=parseInt(el.dataset.gen);const now=Math.floor(Date.now()/1000);el.textContent=_fmt_ago(now-gen);});}
window.addEventListener('DOMContentLoaded',()=>{_tick();setInterval(_tick,1000);});
</script>
"""


@dataclass(frozen=True)
class _TimeAgoAssets:
    css: str
    script: str


timeago_assets = _TimeAgoAssets(css=_TIMEAGO_CSS, script=_TIMEAGO_SCRIPT)


# ---------------------------------------------------------------------------
# Banner helper
# ---------------------------------------------------------------------------


def timeago_banner(label: str = "Generated",
                    extra: str = "") -> str:
    """Return the HTML for the standard top-of-page timeago banner.

    ``label`` prefixes the timeago span (e.g. ``"Generated"``,
    ``"Last updated"``).  ``extra`` is appended after the absolute
    timestamp, with a separator ``" · "``.

    The page must include ``timeago_assets.css`` in its stylesheet
    AND include ``timeago_assets.script`` somewhere in the body so
    the .timeago element gets ticked every second.
    """
    gen_dt = datetime.now(timezone.utc)
    gen_unix = int(gen_dt.timestamp())
    gen_iso = gen_dt.isoformat(timespec="seconds")
    extra_html = f' &middot; {extra}' if extra else ''
    return (
        f'<div class="gen-banner">'
        f'{label} <span class="timeago" data-gen="{gen_unix}">just now</span>'
        f' &middot; <code>{gen_iso}Z</code>'
        f'{extra_html}'
        f'</div>'
    )
