"""
Domain-agnostic task-type knowledge index.

Provides cross-instance / cross-domain prior retrieval:

  TaskSignature     -- compact feature descriptor computed from early
                       observations (zero LLM cost).
  TaskType          -- one entry in the library: signature profile +
                       learned-facts template + canonical concepts.
  TaskTypeLibrary   -- persistent index.  Primary backend: LanceDB
                       (Apache 2.0, embedded, no server).  Automatic
                       fallback: JSON + numpy cosine scan.  Same query
                       API for both backends.
  TypeRetrieval     -- query interface: TaskSignature → [(TaskType, score)]
                       via two-stage retrieval (structural pre-filter then
                       cosine re-rank).

Usage (domain adapter pattern):
    # At session startup, after bootstrap probe:
    from cognitive_os.knowledge_index import TaskTypeLibrary, TypeRetrieval
    library  = TaskTypeLibrary.load_or_create(kb_dir / "task_types",
                                              seed_fn=my_seed_fn)
    results  = TypeRetrieval(library).retrieve(sig, domain="arc-agi-3")
    # results: [(TaskType, confidence_float), ...]  sorted best-first

Backend selection:
    If ``lancedb`` is importable, a LanceDB table is maintained alongside
    the JSON file (Apache Arrow on-disk format, HNSW index, hybrid
    vector+filter queries).  Otherwise the library lives entirely in the
    JSON file and retrieval is a pure-numpy cosine scan.  Both backends
    use the same on-disk JSON as the source of truth; the LanceDB table
    is a derived artifact rebuilt automatically on first access.

Embedding:
    If ``sentence_transformers`` is importable, type descriptions are
    embedded with ``all-MiniLM-L6-v2`` (384-dim, Apache 2.0).  Otherwise
    a normalised 12-dim numeric feature vector is used.  The mode is
    stored in the library metadata; a mode change triggers a one-time
    re-embed of all entries.
"""
from __future__ import annotations

import hashlib
import json
import math
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Callable, Optional

import numpy as np

# ---------------------------------------------------------------------------
# Optional heavy dependencies (graceful fallback when absent)
# ---------------------------------------------------------------------------
try:
    import lancedb as _lancedb          # type: ignore
    import pyarrow as _pa               # type: ignore
    _LANCEDB_OK = True
except ImportError:
    _LANCEDB_OK = False

try:
    from sentence_transformers import SentenceTransformer as _ST  # type: ignore
    _ST_MODEL: Optional["_ST"] = None   # lazy-loaded on first use
    _ST_OK = True
except ImportError:
    _ST_OK = False
    _ST_MODEL = None

# ---------------------------------------------------------------------------
# Numeric feature definitions for the 12-dim fallback vector
# ---------------------------------------------------------------------------
# Each entry: (feature_name, normalisation_scale)
# Value fed into vector = clip(raw / scale, 0, 1)
_FEATURE_DEFS: list[tuple[str, float]] = [
    ("has_movement",                1.0),
    ("max_action_diff_cells",     200.0),
    ("min_action_diff_cells",     200.0),
    ("has_frame_divider",           1.0),
    ("divider_row_frac",            1.0),
    ("palette_count",              32.0),
    ("action_count",               10.0),
    ("requires_coordinates",        1.0),
    ("spatial_action_count",        5.0),
    ("element_action_count",        5.0),
    ("null_action_count",           5.0),
    ("top_bottom_component_ratio",  5.0),
]
_FEATURE_NAMES = [f for f, _ in _FEATURE_DEFS]
_FEATURE_DIM   = len(_FEATURE_DEFS)  # 12

_SCHEMA_VERSION = "1.0"


# ---------------------------------------------------------------------------
# Core data classes
# ---------------------------------------------------------------------------

@dataclass
class TaskSignature:
    """
    Compact descriptor of a new task / game, computed from the zero-LLM
    bootstrap probe phase.  Entirely harness-side; no LLM cost.

    ``domain`` partitions the library (e.g. "arc-agi-3", "robotics").
    ``features`` is a flat dict of named floats / bools; the domain adapter
    decides which keys to populate.  Unknown keys are silently ignored by
    the retrieval logic.
    ``description`` is an optional one-paragraph natural-language summary
    (template-generated by the adapter, not LLM-authored); used for richer
    embeddings when sentence-transformers is available.
    """
    domain: str
    features: dict[str, Any]
    description: str = ""


@dataclass
class TaskType:
    """
    One entry in the task-type library.

    ``type_id``             -- stable identifier, e.g. "arc-agi3/tile-cycle".
    ``domain``              -- matches TaskSignature.domain.
    ``display_name``        -- human-readable label.
    ``signature_profile``   -- feature constraints used in Stage-1 pre-filter.
                               Keys are feature names; values are scalars
                               (exact bool match) or [min, max] ranges.
    ``learned_facts_template`` -- injected into PRIOR_LEARNED_FACTS when this
                               type is matched.  Same schema as per-game
                               learned_facts (action_semantics, game_mechanic,
                               component_roles).
    ``canonical_concepts``  -- type-level concept vocabulary, e.g.
                               {"cycle_action": "action that advances tile"}.
    ``command_constraints`` -- per-command guidance, e.g.
                               {"SYSTEMATIC_EXPLORE": "preferred",
                                "MOVE_TO": "forbidden"}.
    ``base_confidence``     -- confidence ceiling for matches from this type.
    ``description``         -- canonical text description for embedding.
    ``vector``              -- pre-computed embedding (None = not yet embedded).
    ``member_instance_ids`` -- game IDs confirmed to belong to this type.
    ``provenance``          -- {created_at, created_by, confirmed_by, ...}.
    """
    type_id: str
    domain: str
    display_name: str
    signature_profile: dict[str, Any]
    learned_facts_template: dict[str, Any]
    canonical_concepts: dict[str, str]
    command_constraints: dict[str, str]
    base_confidence: float
    description: str
    vector: Optional[list[float]]
    member_instance_ids: list[str] = field(default_factory=list)
    provenance: dict[str, Any] = field(default_factory=dict)

    # ------------------------------------------------------------------
    # Content-addressed stable ID (for dedup / merge)
    # ------------------------------------------------------------------
    @staticmethod
    def canonical_id(domain: str, type_id: str) -> str:
        """SHA-256 hash of (domain, type_id) → 16-char hex prefix."""
        raw = json.dumps({"domain": domain, "type_id": type_id},
                         sort_keys=True)
        return hashlib.sha256(raw.encode()).hexdigest()[:16]

    def content_hash(self) -> str:
        return TaskType.canonical_id(self.domain, self.type_id)


# ---------------------------------------------------------------------------
# Embedding helpers
# ---------------------------------------------------------------------------

def _feature_vector(features: dict[str, Any]) -> np.ndarray:
    """
    Build the 12-dim normalised feature vector from a features dict.
    Missing keys default to 0.  Output is L2-normalised (unit vector).
    """
    vec = np.zeros(_FEATURE_DIM, dtype=np.float32)
    for i, (name, scale) in enumerate(_FEATURE_DEFS):
        raw = features.get(name, 0)
        vec[i] = float(bool(raw) if isinstance(raw, bool) else raw) / scale
    vec = np.clip(vec, 0.0, 1.0)
    norm = float(np.linalg.norm(vec))
    if norm > 1e-9:
        vec /= norm
    return vec


def _st_embed(text: str) -> np.ndarray:
    """
    Embed ``text`` with sentence-transformers/all-MiniLM-L6-v2 (384-dim).
    Lazy-loads the model on first call.  Falls back to feature vector if the
    import fails at runtime.
    """
    global _ST_MODEL
    if not _ST_OK:
        raise RuntimeError("sentence_transformers not installed")
    if _ST_MODEL is None:
        _ST_MODEL = _ST("all-MiniLM-L6-v2")
    vec = _ST_MODEL.encode(text, normalize_embeddings=True)
    return np.array(vec, dtype=np.float32)


def _embed(features: dict[str, Any], description: str) -> np.ndarray:
    """
    Compute embedding vector for a signature or type entry.
    Uses sentence-transformers when available (384-dim, semantically rich);
    falls back to normalised numeric feature vector (12-dim, always works).
    """
    if _ST_OK and description:
        try:
            return _st_embed(description)
        except Exception:
            pass
    return _feature_vector(features)


def _embed_mode() -> str:
    return "sentence_transformer_384" if _ST_OK else "feature_vector_12"


def _embed_dim() -> int:
    return 384 if _ST_OK else _FEATURE_DIM


def _cosine(a: np.ndarray, b: np.ndarray) -> float:
    na = float(np.linalg.norm(a))
    nb = float(np.linalg.norm(b))
    if na < 1e-9 or nb < 1e-9:
        return 0.0
    return float(np.dot(a, b)) / (na * nb)


# ---------------------------------------------------------------------------
# Storage: JSON + numpy backend (always available)
# ---------------------------------------------------------------------------

class _JsonNumpyBackend:
    """
    Persistent JSON file + in-memory numpy cosine scan.
    Source of truth: ``<db_path>.json``.
    Suitable for < ~10 000 types; no extra dependencies.
    """

    def __init__(self, json_path: Path):
        self._path = json_path
        self._types: list[TaskType] = []
        self._vectors: list[np.ndarray] = []
        self._meta: dict[str, Any] = {
            "schema_version": _SCHEMA_VERSION,
            "embedding_mode": _embed_mode(),
            "embedding_dim": _embed_dim(),
        }

    # ---- persistence ----

    def save(self) -> None:
        self._path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            **self._meta,
            "types": [
                {**asdict(t), "vector": (t.vector or [])}
                for t in self._types
            ],
        }
        with open(self._path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)

    @classmethod
    def load(cls, json_path: Path) -> "_JsonNumpyBackend":
        backend = cls(json_path)
        if not json_path.exists():
            return backend
        with open(json_path, encoding="utf-8") as f:
            payload = json.load(f)
        backend._meta = {k: v for k, v in payload.items() if k != "types"}
        for raw in payload.get("types", []):
            vec_list: list[float] = raw.pop("vector", [])
            raw["vector"] = vec_list if vec_list else None
            t = TaskType(**raw)
            backend._types.append(t)
            if t.vector:
                backend._vectors.append(np.array(t.vector, dtype=np.float32))
            else:
                backend._vectors.append(np.zeros(_embed_dim(), dtype=np.float32))
        return backend

    # ---- mutation ----

    def add_or_update(self, t: TaskType) -> None:
        """Insert or replace a type by type_id."""
        if t.vector is None:
            vec = _embed(t.signature_profile.get("_features", {}),
                         t.description)
            t.vector = vec.tolist()
        vec_arr = np.array(t.vector, dtype=np.float32)

        for i, existing in enumerate(self._types):
            if existing.type_id == t.type_id and existing.domain == t.domain:
                self._types[i] = t
                self._vectors[i] = vec_arr
                return
        self._types.append(t)
        self._vectors.append(vec_arr)

    # ---- retrieval ----

    def query(self, sig: TaskSignature, top_k: int,
              pre_filter_fn: Callable[[TaskType], bool]) -> list[tuple[TaskType, float]]:
        """
        Stage-1 pre-filter via ``pre_filter_fn``, then Stage-2 cosine rank.
        Returns up to ``top_k`` (type, score) pairs sorted best-first.
        """
        q_vec = _embed(sig.features, sig.description)

        candidates: list[tuple[int, TaskType]] = [
            (i, t) for i, t in enumerate(self._types)
            if pre_filter_fn(t)
        ]
        if not candidates:
            return []

        scored: list[tuple[float, TaskType]] = []
        for i, t in candidates:
            score = _cosine(q_vec, self._vectors[i])
            scored.append((score, t))

        scored.sort(key=lambda x: x[0], reverse=True)
        return [(t, s) for s, t in scored[:top_k]]

    # ---- re-embed if mode changed ----

    def ensure_embeddings_current(self) -> int:
        """Re-embed all entries if embedding mode has changed. Returns count."""
        stored_mode = self._meta.get("embedding_mode", "")
        current_mode = _embed_mode()
        if stored_mode == current_mode:
            return 0
        print(f"[knowledge_index] embedding mode changed "
              f"{stored_mode!r} → {current_mode!r}; re-embedding {len(self._types)} types")
        for i, t in enumerate(self._types):
            vec = _embed(t.signature_profile.get("_features", {}), t.description)
            t.vector = vec.tolist()
            self._vectors[i] = vec
        self._meta["embedding_mode"] = current_mode
        self._meta["embedding_dim"] = _embed_dim()
        return len(self._types)


# ---------------------------------------------------------------------------
# Storage: LanceDB backend (when available)
# ---------------------------------------------------------------------------

class _LanceDBBackend:
    """
    LanceDB-backed store.  Source of truth is still the JSON file; the Lance
    table is a derived artifact that is rebuilt automatically when the JSON
    is newer.  Provides HNSW-indexed cosine ANN and native payload filtering.
    """

    _TABLE = "task_types"

    def __init__(self, db_dir: Path, json_path: Path):
        self._db_dir = db_dir
        self._json_path = json_path
        self._json_backend = _JsonNumpyBackend.load(json_path)
        self._db = _lancedb.connect(str(db_dir / "lance"))
        self._table = self._ensure_table()

    def _ensure_table(self):
        """Create or re-sync the Lance table from JSON."""
        dim = _embed_dim()
        schema = _pa.schema([
            _pa.field("type_id",        _pa.string()),
            _pa.field("domain",         _pa.string()),
            _pa.field("display_name",   _pa.string()),
            _pa.field("base_confidence",_pa.float32()),
            _pa.field("has_movement",   _pa.bool_()),
            _pa.field("has_frame_divider", _pa.bool_()),
            _pa.field("requires_coordinates", _pa.bool_()),
            _pa.field("description",    _pa.string()),
            _pa.field("metadata_json",  _pa.string()),  # full TaskType as JSON
            _pa.field("vector",         _pa.list_(_pa.float32(), dim)),
        ])
        try:
            tbl = self._db.open_table(self._TABLE)
        except Exception:
            tbl = self._db.create_table(self._TABLE,
                                        schema=schema, mode="create")
        # Sync any entries from JSON not yet in Lance
        existing_ids = set(tbl.to_pandas()["type_id"].tolist()) if len(tbl) > 0 else set()
        new_rows = []
        for t in self._json_backend._types:
            if t.type_id not in existing_ids:
                new_rows.append(self._type_to_row(t, dim))
        if new_rows:
            tbl.add(new_rows)
        return tbl

    def _type_to_row(self, t: TaskType, dim: int) -> dict:
        vec = t.vector or [0.0] * dim
        if len(vec) != dim:
            vec = vec[:dim] + [0.0] * max(0, dim - len(vec))
        profile = t.signature_profile
        return {
            "type_id":              t.type_id,
            "domain":               t.domain,
            "display_name":         t.display_name,
            "base_confidence":      float(t.base_confidence),
            "has_movement":         bool(profile.get("has_movement", False)),
            "has_frame_divider":    bool(profile.get("has_frame_divider", False)),
            "requires_coordinates": bool(profile.get("requires_coordinates", False)),
            "description":          t.description,
            "metadata_json":        json.dumps(asdict(t)),
            "vector":               [float(v) for v in vec],
        }

    def save(self) -> None:
        self._json_backend.save()

    def add_or_update(self, t: TaskType) -> None:
        self._json_backend.add_or_update(t)
        # Upsert into Lance table
        dim = _embed_dim()
        row = self._type_to_row(t, dim)
        try:
            self._table.delete(f"type_id = '{t.type_id}'")
        except Exception:
            pass
        self._table.add([row])

    def query(self, sig: TaskSignature, top_k: int,
              pre_filter_fn: Callable[[TaskType], bool]) -> list[tuple[TaskType, float]]:
        q_vec = _embed(sig.features, sig.description)

        # Build Lance where-clause from signature hard constraints
        clauses = [f"domain = '{sig.domain}'"]
        if "has_movement" in sig.features:
            clauses.append(f"has_movement = {str(sig.features['has_movement']).lower()}")
        where = " AND ".join(clauses)

        try:
            df = (self._table.search(q_vec.tolist())
                  .where(where)
                  .metric("cosine")
                  .limit(top_k * 3)   # oversample for post-filter
                  .to_pandas())
        except Exception:
            # Fall back to JSON backend on any Lance error
            return self._json_backend.query(sig, top_k, pre_filter_fn)

        results: list[tuple[TaskType, float]] = []
        for _, row in df.iterrows():
            try:
                raw = json.loads(row["metadata_json"])
                t = TaskType(**raw)
            except Exception:
                continue
            if not pre_filter_fn(t):
                continue
            score = float(1.0 - row.get("_distance", 0.0))  # Lance returns distance
            results.append((t, score))
            if len(results) >= top_k:
                break
        return results

    def ensure_embeddings_current(self) -> int:
        n = self._json_backend.ensure_embeddings_current()
        if n:
            # Rebuild Lance table
            try:
                self._db.drop_table(self._TABLE)
            except Exception:
                pass
            self._table = self._ensure_table()
        return n


# ---------------------------------------------------------------------------
# TaskTypeLibrary — public API
# ---------------------------------------------------------------------------

class TaskTypeLibrary:
    """
    Persistent task-type knowledge index.

    The JSON file is always written and is the source of truth.
    LanceDB is used when available for scalable ANN retrieval.

    Typical usage::

        library = TaskTypeLibrary.load_or_create(
            Path("cognitive_os/knowledge/task_types"),
            seed_fn=my_domain_seed_fn   # called only when library is empty
        )
        results = TypeRetrieval(library).retrieve(sig, domain="arc-agi-3")
    """

    def __init__(self, db_path: Path):
        self._db_path = db_path
        json_path = db_path.with_suffix(".json")
        if _LANCEDB_OK:
            self._backend: _JsonNumpyBackend | _LanceDBBackend = \
                _LanceDBBackend(db_path, json_path)
            print(f"[knowledge_index] LanceDB backend active at {db_path}")
        else:
            self._backend = _JsonNumpyBackend.load(json_path)
            print(f"[knowledge_index] JSON+numpy backend active "
                  f"({len(self._backend._types)} types loaded)")

    # ---- factory ----

    @classmethod
    def load_or_create(
        cls,
        db_path: Path,
        seed_fn: Optional[Callable[["TaskTypeLibrary"], None]] = None,
    ) -> "TaskTypeLibrary":
        """
        Load the library from ``db_path``.  If it is empty (first run) and
        ``seed_fn`` is provided, call it to populate the initial type entries,
        then save.
        """
        lib = cls(db_path)
        if len(lib) == 0 and seed_fn is not None:
            print("[knowledge_index] library is empty — running seed function")
            seed_fn(lib)
            lib.save()
            print(f"[knowledge_index] seeded {len(lib)} type(s)")
        lib._backend.ensure_embeddings_current()
        return lib

    # ---- mutation ----

    def add_type(self, t: TaskType) -> None:
        """Insert or replace a type.  Computes embedding if vector is None."""
        if not t.provenance:
            t.provenance = {
                "created_at": _iso_now(),
                "created_by": "api",
            }
        self._backend.add_or_update(t)

    def confirm_instance(self, type_id: str, domain: str,
                         instance_id: str) -> None:
        """Record that ``instance_id`` confirmed this type."""
        for t in self._backend._types:
            if t.type_id == type_id and t.domain == domain:
                if instance_id not in t.member_instance_ids:
                    t.member_instance_ids.append(instance_id)
                if "confirmed_by" not in t.provenance:
                    t.provenance["confirmed_by"] = []
                if instance_id not in t.provenance["confirmed_by"]:
                    t.provenance["confirmed_by"].append(instance_id)
                break

    def save(self) -> None:
        self._backend.save()

    # ---- query ----

    def query(self, sig: TaskSignature, top_k: int = 5,
              pre_filter_fn: Optional[Callable[[TaskType], bool]] = None,
              ) -> list[tuple[TaskType, float]]:
        """
        Return up to ``top_k`` (TaskType, cosine_score) pairs for ``sig``,
        sorted best-first.  ``pre_filter_fn`` is the Stage-1 hard filter;
        defaults to domain equality check.
        """
        if pre_filter_fn is None:
            def pre_filter_fn(t: TaskType) -> bool:
                return t.domain == sig.domain

        return self._backend.query(sig, top_k, pre_filter_fn)

    def __len__(self) -> int:
        return len(self._backend._types)

    def all_types(self) -> list[TaskType]:
        return list(self._backend._types)


# ---------------------------------------------------------------------------
# TypeRetrieval — high-level interface with confidence gating
# ---------------------------------------------------------------------------

# Retrieval result container
@dataclass
class RetrievalResult:
    matches: list[tuple[TaskType, float]]   # sorted best-first
    top_type: Optional[TaskType]
    top_score: float
    injected: bool                          # True if prior should be injected
    prior_text: str                         # formatted for PRIOR_LEARNED_FACTS

    def __bool__(self) -> bool:
        return self.injected


class TypeRetrieval:
    """
    Query wrapper around TaskTypeLibrary.  Handles:
      - Stage-1 pre-filter (domain + key boolean features)
      - Stage-2 cosine re-rank
      - Confidence gating (inject / blend / start-cold decision)
      - Formatting the retrieved prior for PRIOR_LEARNED_FACTS injection
    """

    GATE_FULL    = 0.85   # inject fully, no caveat
    GATE_PARTIAL = 0.65   # inject with confidence label
    GATE_BLEND   = 0.55   # second type also injected when top ≥ GATE_PARTIAL
    GATE_COLD    = 0.0    # below GATE_PARTIAL → start cold

    def __init__(self, library: TaskTypeLibrary,
                 gate_full: float = GATE_FULL,
                 gate_partial: float = GATE_PARTIAL,
                 gate_blend: float = GATE_BLEND):
        self._lib = library
        self.gate_full    = gate_full
        self.gate_partial = gate_partial
        self.gate_blend   = gate_blend

    def retrieve(self, sig: TaskSignature,
                 domain: Optional[str] = None,
                 top_k: int = 3) -> RetrievalResult:
        """
        Retrieve and format the best matching type(s) for ``sig``.

        Returns a ``RetrievalResult`` whose ``.injected`` is True when the
        confidence gate is met, and ``.prior_text`` contains the formatted
        PRIOR_LEARNED_FACTS block to prepend.
        """
        _domain = domain or sig.domain

        # Stage-1 pre-filter: domain + key booleans
        def _filter(t: TaskType) -> bool:
            if t.domain != _domain:
                return False
            prof = t.signature_profile
            # Hard gate on has_movement (most discriminating)
            if "has_movement" in prof:
                if bool(sig.features.get("has_movement", False)) != bool(prof["has_movement"]):
                    return False
            return True

        matches = self._lib.query(sig, top_k=top_k, pre_filter_fn=_filter)
        if not matches:
            return RetrievalResult([], None, 0.0, False, "")

        top_type, top_score = matches[0]
        top_score = min(top_score, top_type.base_confidence)  # cap by type confidence

        if top_score < self.gate_partial:
            return RetrievalResult(matches, top_type, top_score, False,
                                   "  (no type-library match above confidence threshold)")

        # Decide which types to inject
        to_inject: list[tuple[TaskType, float]] = [(top_type, top_score)]
        if len(matches) >= 2:
            t2, s2 = matches[1]
            s2 = min(s2, t2.base_confidence)
            if s2 >= self.gate_blend and top_score < self.gate_full:
                to_inject.append((t2, s2))

        injected = True
        prior_text = _format_prior(to_inject, self.gate_full)
        return RetrievalResult(matches, top_type, top_score, injected, prior_text)


# ---------------------------------------------------------------------------
# PRIOR_LEARNED_FACTS formatter
# ---------------------------------------------------------------------------

def _format_prior(matches: list[tuple[TaskType, float]],
                  gate_full: float) -> str:
    lines = []
    for t, score in matches:
        conf_label = (
            f"confidence={score:.2f}"
            if score < gate_full
            else "high confidence"
        )
        lines.append(
            f"  [TYPE LIBRARY PRIOR — \"{t.display_name}\", {conf_label}]"
        )
        lft = t.learned_facts_template
        _as = lft.get("action_semantics") or {}
        if _as:
            lines.append("  ACTION SEMANTICS (type-level defaults):")
            for a, s in sorted(_as.items()):
                lines.append(f"    {a}: {s}")
        _gm = lft.get("game_mechanic")
        if _gm:
            lines.append(f"  GAME MECHANIC (type-level): {_gm}")
        if t.command_constraints:
            lines.append("  COMMAND GUIDANCE:")
            for cmd, guidance in t.command_constraints.items():
                lines.append(f"    {cmd}: {guidance}")
        if t.canonical_concepts:
            lines.append("  CANONICAL CONCEPTS:")
            for concept, desc in t.canonical_concepts.items():
                lines.append(f"    {concept}: {desc}")
        lines.append("")  # blank separator between multiple matches
    return "\n".join(lines).rstrip()


# ---------------------------------------------------------------------------
# Merge utility
# ---------------------------------------------------------------------------

def merge_libraries(base: TaskTypeLibrary,
                    incoming: TaskTypeLibrary,
                    sim_threshold_dedup: float = 0.95,
                    sim_threshold_related: float = 0.70,
                    ) -> tuple[int, int, int]:
    """
    Merge ``incoming`` into ``base`` in-place.

    Returns (exact_dupes, near_dupes_flagged, new_types_added).
    """
    exact_dupes = near_dupes = new_added = 0

    for t_in in incoming.all_types():
        # 1. Exact hash match
        existing_ids = {t.type_id for t in base.all_types()
                        if t.domain == t_in.domain}
        if t_in.type_id in existing_ids:
            exact_dupes += 1
            # Merge member lists and update confidence
            for t_base in base.all_types():
                if t_base.type_id == t_in.type_id:
                    merged = list(set(t_base.member_instance_ids +
                                      t_in.member_instance_ids))
                    t_base.member_instance_ids = merged
                    t_base.base_confidence = max(t_base.base_confidence,
                                                 t_in.base_confidence)
                    break
            continue

        # 2. Similarity check
        sig = TaskSignature(
            domain=t_in.domain,
            features=t_in.signature_profile.get("_features", {}),
            description=t_in.description,
        )
        results = base.query(sig, top_k=1)
        if results:
            _, sim = results[0]
            if sim >= sim_threshold_dedup:
                near_dupes += 1
                # Flag as near-duplicate in provenance
                t_in.provenance["near_duplicate_of"] = results[0][0].type_id
                t_in.provenance["near_duplicate_sim"] = round(sim, 3)
                base.add_type(t_in)   # keep both
                continue
            elif sim >= sim_threshold_related:
                near_dupes += 1
                t_in.provenance["related_to"] = results[0][0].type_id
                base.add_type(t_in)
                new_added += 1
                continue

        # 3. Novel type
        base.add_type(t_in)
        new_added += 1

    return exact_dupes, near_dupes, new_added


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _iso_now() -> str:
    import datetime
    return datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
